### PR TITLE
there are no minimized versions anymore

### LINKED ISSUE #50: Export to Codepen not working
* Release number or git hash: https://lineup.js.org/app/
 * Web browser version and OS: FF 74

### Steps to reproduce

 1. Go to https://lineup.js.org/app/#soccer
 2. Export to Codepen

### Observed behavior
 * Any unexpected output or action (or lack of expected output or action)

No lineup  displayed

 * Web browser console errors (including tracebacks)
```
The resource from “https://unpkg.com/lineupjs@3.3.0/build/LineUpJS.min.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff). index.html

The resource from “https://unpkg.com/lineupjs@3.3.0/build/LineUpJS.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff). index.html

```
```
ReferenceError: LineUpJS is not defined
```

 * ~Server errors (relevant messages and tracebacks)~
 * Static or animated images showing the UI behavior

image

### Workaround
Open Pen settings and switch to non-minified css and js files.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #50 

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 

### Summary
 
there are no explicit minimized versions anymore

### CODE REVIEW

**Comment by thinkh** [comment]
Why and when did we remove the minified files?

**Comment by sgratzl** [comment]
cause the regular files are already the minimized version in a production case, see e.g. https://unpkg.com/lineupjs@3.3.0/build/LineUpJS.js

**Comment by thinkh** [comment]
Thanks, got it! Did you intentionally want to merge this into the master branch? Otherwise I would merge it into the develop branch as usual.

**Comment by sgratzl** [comment]
master -> lineup.js v3 -> lineup.js.org/app
develop -> lineup.js v4 which uses a different way to export data  -> lineup.js.org/app_develop

isn't it?

**Comment by thinkh** [comment]
Sorry, I missed that we are in LineUp App... Yes, you are right. 👍

**Pull request merged**
